import * as anchor from "@coral-xyz/anchor";
import { PublicKey } from "@solana/web3.js";

// Oracle program interface - would typically be auto-generated by Anchor
export type Oracle = {
  "version": "0.1.0",
  "name": "shin2chin-oracle",
  "instructions": [
    {
      "name": "registerOracle",
      "accounts": [
        {
          "name": "admin",
          "isMut": true,
          "isSigner": true
        },
        {
          "name": "oracle",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "oracleAuthority",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "systemProgram",
          "isMut": false,
          "isSigner": false
        }
      ],
      "args": [
        {
          "name": "oracleName",
          "type": "string"
        },
        {
          "name": "oracleAuthority",
          "type": "publicKey"
        }
      ]
    },
    {
      "name": "submitResult",
      "accounts": [
        {
          "name": "oracleAuthority",
          "isMut": true,
          "isSigner": true
        },
        {
          "name": "oracle",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "event",
          "isMut": true,
          "isSigner": false
        }
      ],
      "args": [
        {
          "name": "teamAScore",
          "type": "u32"
        },
        {
          "name": "teamBScore",
          "type": "u32"
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "Oracle",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "authority",
            "type": "publicKey"
          },
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "submissionsCount",
            "type": "u64"
          },
          {
            "name": "lastSubmission",
            "type": "i64"
          },
          {
            "name": "reserved",
            "type": {
              "array": [
                "u8",
                64
              ]
            }
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    }
  ]
};

// Helper functions for client-side interaction
export class OracleClient {
  program: anchor.Program<Oracle>;
  
  constructor(program: anchor.Program<Oracle>) {
    this.program = program;
  }
  
  // Find the PDA for an oracle account
  async findOracleAddress(authority: PublicKey): Promise<[PublicKey, number]> {
    return await PublicKey.findProgramAddress(
      [Buffer.from("oracle"), authority.toBuffer()],
      this.program.programId
    );
  }
}